# Generated by Django 3.0.4 on 2020-06-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplications',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='creditapplications',
            name='term',
        ),
        migrations.AddField(
            model_name='creditsdocuments',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='es valido'),
        ),
        migrations.AlterField(
            model_name='creditapplications',
            name='payment_periodicity',
            field=models.CharField(default='Quincenal', max_length=15, verbose_name='frecuencia de pago'),
        ),
        migrations.AlterField(
            model_name='creditapplications',
            name='person_type',
            field=models.CharField(blank=True, default='Persona física', max_length=6, verbose_name='tipo contribuyente'),
        ),
    ]
