# Generated by Django 3.0.4 on 2020-06-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200528_2030'),
        ('credits', '0002_auto_20200608_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplications',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='producto'),
        ),
    ]
