# Generated by Django 3.0.4 on 2020-06-17 00:03

import credits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_auto_20200611_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplicationjobs',
            name='workplace',
            field=models.CharField(max_length=80, verbose_name='area de trabajo'),
        ),
        migrations.AlterField(
            model_name='creditsdocuments',
            name='path',
            field=models.FileField(upload_to=credits.models.credit_application_path),
        ),
    ]
