# Generated by Django 3.0.4 on 2020-07-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_auto_20200617_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplications',
            name='person_type',
        ),
        migrations.AddField(
            model_name='creditapplicationpartnership',
            name='phone_contact',
            field=models.CharField(max_length=13, null=True, verbose_name='telefono de contacto'),
        ),
        migrations.AddField(
            model_name='creditapplicationsreferences',
            name='reference_number',
            field=models.PositiveIntegerField(default=1, verbose_name='num. de referencia'),
        ),
    ]
