# Generated by Django 3.0.4 on 2020-07-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_auto_20200709_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdocuments',
            name='fimubac_key',
            field=models.CharField(blank=True, max_length=5, verbose_name='clave FIMUBAC'),
        ),
    ]
