# Generated by Django 3.0.4 on 2020-08-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_catdocuments_fimubac_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplications',
            name='final_fortnight',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='creditapplications',
            name='initial_fortnight',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
