# Generated by Django 3.0.4 on 2020-08-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_auto_20200814_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplicationjobs',
            name='employee_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
