# Generated by Django 3.0.4 on 2020-08-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_creditapplications_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplications',
            name='total_loan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='total del préstamo'),
        ),
    ]
