# Generated by Django 3.0.4 on 2020-09-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0008_genders_gendersinvestor'),
        ('credits', '0013_creditapplications_total_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplications',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.Banks'),
        ),
    ]
