# Generated by Django 3.0.4 on 2020-09-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_auto_20200824_1703'),
        ('products', '0008_auto_20200817_1948'),
        ('credits', '0014_auto_20200909_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplications',
            name='agreement',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='agreements.Agreements', verbose_name='convenio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditapplications',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='producto'),
        ),
    ]
