# Generated by Django 3.0.4 on 2020-09-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0015_auto_20200910_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplicationjobs',
            name='organization_id',
        ),
    ]
