# Generated by Django 3.0.4 on 2020-09-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0018_auto_20200916_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditapplicationpartnership',
            old_name='last_name',
            new_name='father_last_name',
        ),
        migrations.RenameField(
            model_name='creditapplicationsreferences',
            old_name='last_name',
            new_name='father_last_name',
        ),
        migrations.AlterField(
            model_name='creditapplicationpartnership',
            name='phone_contact',
            field=models.CharField(max_length=10, null=True, verbose_name='telefono de contacto'),
        ),
    ]
