# Generated by Django 3.0.4 on 2020-09-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_auto_20200923_1712'),
        ('advisers', '0003_auto_20200923_1722'),
        ('catalogues', '0012_creditstatus_creditstatusinvestor'),
        ('credits', '0020_auto_20200917_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplications',
            name='final_fortnight',
        ),
        migrations.RemoveField(
            model_name='creditapplications',
            name='initial_fortnight',
        ),
        migrations.AddField(
            model_name='creditapplications',
            name='adviser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='advisers.Advisers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditapplications',
            name='branch_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='offices.BranchOffices'),
        ),
        migrations.AlterField(
            model_name='creditapplications',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.CreditStatus', verbose_name='estatus'),
        ),
        migrations.DeleteModel(
            name='CatCreditStatus',
        ),
    ]
