# Generated by Django 3.0.4 on 2020-11-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0013_identifications_identificationsinvestor'),
        ('credits', '0022_auto_20200928_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplicationjobs',
            name='ife_ine',
        ),
        migrations.AddField(
            model_name='creditapplications',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Identicación'),
        ),
        migrations.AddField(
            model_name='creditapplications',
            name='identification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogues.Identifications'),
        ),
    ]
