# Generated by Django 3.0.4 on 2020-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0023_auto_20201111_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplications',
            name='id_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Identificación'),
        ),
    ]
