# Generated by Django 3.0.4 on 2020-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0024_auto_20201118_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplications',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='creditapplications',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='creditapplications',
            name='total_loan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total del préstamo'),
        ),
    ]
