# Generated by Django 3.0.4 on 2020-12-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0025_auto_20201119_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('dist_capital', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dist_intereses', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dist_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='credits.CreditApplications')),
            ],
            options={
                'db_table': 'TCA011',
            },
        ),
    ]
