# Generated by Django 3.0.4 on 2020-08-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizationtable',
            name='fortnightly_number',
            field=models.CharField(max_length=6, verbose_name='Num. de quincena'),
        ),
    ]
