# Generated by Django 3.0.4 on 2020-12-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortization', '0005_auto_20201211_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationtable',
            name='capital_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='amortizationtable',
            name='interes_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='amortizationtable',
            name='iva_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amortizationtable',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='monto pagado'),
        ),
    ]
