# Generated by Django 3.0.4 on 2020-05-08 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('alias', models.CharField(max_length=15, verbose_name='alias')),
                ('business_name', models.CharField(max_length=200, verbose_name='razón social')),
                ('business_activity', models.CharField(max_length=30, verbose_name='tipo de negocio')),
                ('state_owned', models.BooleanField(default=False, verbose_name='pertenece al estado')),
                ('federal_owned', models.BooleanField(default=False, verbose_name='pertenece a la federación')),
                ('organization_type', models.CharField(max_length=30, verbose_name='tipo de dependencia')),
                ('legal_representative', models.CharField(max_length=150, verbose_name='representante legal')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de desactivación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('deactivated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='desactivada por')),
            ],
            options={
                'db_table': 'TO001',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('address_name', models.CharField(max_length=30, verbose_name='identificador')),
                ('street', models.CharField(max_length=50, verbose_name='calle')),
                ('exterior_number', models.CharField(max_length=15, verbose_name='numero exterior')),
                ('interior_number', models.CharField(max_length=15, verbose_name='numero interior')),
                ('suburb', models.CharField(max_length=50, verbose_name='colonia/fracc')),
                ('zip_code', models.CharField(max_length=5, verbose_name='código postal')),
                ('city', models.CharField(max_length=25, verbose_name='ciudad')),
                ('state', models.CharField(max_length=25, verbose_name='estado')),
                ('phone_contact', models.CharField(max_length=13, verbose_name='teléfono de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de desactivación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_adr_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('deactivated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_adr_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='desactivada por')),
                ('organization_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
            options={
                'db_table': 'TOA002',
            },
        ),
    ]
