# Generated by Django 3.0.4 on 2020-06-02 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='nombre del contacto')),
                ('position', models.CharField(max_length=50, verbose_name='puesto')),
                ('phone_contact', models.CharField(max_length=13, verbose_name='telefono de contacto')),
                ('email', models.EmailField(max_length=100, verbose_name='correo electronico')),
                ('desc_activity', models.TextField(help_text='Describe la actividad que se revisa con el contacto: instalaciones, pagos, trámites', verbose_name='descripcion de la actividad')),
                ('birthdate', models.DateField(blank=True, verbose_name='fecha de nacimiento')),
                ('comments', models.TextField(help_text='Comentarios adicionales sobre el contacto', verbose_name='comentarios')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
            options={
                'db_table': 'TOC013',
            },
        ),
    ]
