# Generated by Django 3.0.4 on 2020-07-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200601_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontacts',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='organizationcontacts',
            name='comments',
            field=models.TextField(blank=True, help_text='Comentarios adicionales sobre el contacto', verbose_name='comentarios'),
        ),
        migrations.AlterField(
            model_name='organizationcontacts',
            name='desc_activity',
            field=models.TextField(blank=True, help_text='Describe la actividad que se revisa con el contacto: instalaciones, pagos, trámites', verbose_name='descripcion de la actividad'),
        ),
    ]
