# Generated by Django 3.0.4 on 2020-08-27 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_auto_20200827_1843'),
        ('organizations', '0004_auto_20200731_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaddress',
            name='state_id',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.PROTECT, to='catalogues.States'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationcontacts',
            name='phone_contact',
            field=models.CharField(max_length=10, verbose_name='telefono de contacto'),
        ),
    ]
