# Generated by Django 3.0.4 on 2020-08-28 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_auto_20200827_1843'),
        ('organizations', '0007_organizationinvestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaddress',
            name='state_id',
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.States'),
        ),
    ]
