# Generated by Django 3.0.4 on 2020-08-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20200827_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationInvestor',
        ),
    ]
