# Generated by Django 3.0.4 on 2020-09-20 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20200919_2116'),
        ('organizations', '0010_auto_20200918_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='branch_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='offices.BranchOffices'),
        ),
    ]
