# Generated by Django 3.0.4 on 2020-09-22 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0011_organization_branch_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontacts',
            name='created_by',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, related_name='org_cont_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationcontacts',
            name='deactivated_at',
            field=models.DateTimeField(null=True, verbose_name='fecha de desactivación'),
        ),
        migrations.AddField(
            model_name='organizationcontacts',
            name='deactivated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_cont_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationcontacts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
