# Generated by Django 3.0.4 on 2020-05-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=80, verbose_name='nombres')),
                ('father_lastname', models.CharField(max_length=50, verbose_name='apellido paterno')),
                ('mother_lastname', models.CharField(blank=True, max_length=50, verbose_name='apellido materno')),
                ('marital_status', models.CharField(max_length=20, verbose_name='estado civil')),
                ('born_place', models.CharField(max_length=50, verbose_name='lugar de nacimiento')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('I', 'No definido')], default='I', max_length=1, verbose_name='sexo')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('RFC', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('CURP', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('FIEL', models.CharField(blank=True, max_length=18, verbose_name='FIEL')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de desactivación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deactivated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='desactivado por')),
            ],
            options={
                'db_table': 'TC007',
            },
        ),
        migrations.CreateModel(
            name='ClientsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('address_name', models.CharField(max_length=30, verbose_name='identificador')),
                ('street', models.CharField(max_length=50, verbose_name='calle')),
                ('ext_number', models.CharField(max_length=15, verbose_name='numero exterior')),
                ('int_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='numero interior')),
                ('suburb', models.CharField(max_length=50, verbose_name='colonia')),
                ('zip_code', models.CharField(max_length=5, verbose_name='codigo Postal')),
                ('city', models.CharField(max_length=25, verbose_name='ciudad')),
                ('state', models.CharField(max_length=25, verbose_name='estado')),
                ('phone_contact', models.CharField(max_length=13, verbose_name='telefono de contacto')),
                ('ubication_references', models.CharField(max_length=150, verbose_name='referencias de ubicacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de desactivación')),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', verbose_name='cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_address_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deactivated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_address_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='desactivado por')),
            ],
            options={
                'db_table': 'TCA008',
            },
        ),
    ]
