# Generated by Django 3.0.4 on 2020-07-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='FIEL',
        ),
    ]
