# Generated by Django 3.0.4 on 2020-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_fiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.DateField(blank=True, null=True, verbose_name='correo electronico'),
        ),
    ]
