# Generated by Django 3.0.4 on 2020-08-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(blank=True, max_length=95, null=True, verbose_name='correo electronico'),
        ),
    ]
