# Generated by Django 3.0.4 on 2020-08-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200812_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='RFC',
            field=models.CharField(max_length=13, unique=True, verbose_name='RFC'),
        ),
    ]
