# Generated by Django 3.0.4 on 2020-09-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0007_maritalstatus_maritalstatusinvestor'),
        ('clients', '0005_auto_20200814_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.MaritalStatus'),
        ),
    ]
