# Generated by Django 3.0.4 on 2020-09-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200903_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsaddress',
            old_name='phone_contact',
            new_name='landline_phone',
        ),
    ]
