# Generated by Django 3.0.4 on 2020-09-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20200903_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaddress',
            name='landline_phone',
            field=models.CharField(max_length=10, verbose_name='telefono de contacto'),
        ),
    ]
