# Generated by Django 3.0.4 on 2020-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200903_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsaddress',
            name='altern_phone',
            field=models.CharField(max_length=10, null=True, verbose_name='telefono alternativo'),
        ),
        migrations.AddField(
            model_name='clientsaddress',
            name='mobile_phone',
            field=models.CharField(max_length=10, null=True, verbose_name='telefono celular'),
        ),
    ]
