# Generated by Django 3.0.4 on 2020-09-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20200903_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsaddress',
            old_name='altern_phone',
            new_name='alternate_phone',
        ),
    ]
