# Generated by Django 3.0.4 on 2020-09-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0007_maritalstatus_maritalstatusinvestor'),
        ('clients', '0011_auto_20200907_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='born_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.States'),
        ),
        migrations.AlterField(
            model_name='clientsaddress',
            name='ext_number',
            field=models.CharField(max_length=50, verbose_name='numero exterior'),
        ),
        migrations.AlterField(
            model_name='clientsaddress',
            name='int_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numero interior'),
        ),
    ]
