# Generated by Django 3.0.4 on 2020-09-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0009_maritalregime_maritalregimeinvestor'),
        ('clients', '0013_auto_20200908_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='marital_regime',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='catalogues.MaritalRegime'),
            preserve_default=False,
        ),
    ]
