# Generated by Django 3.0.4 on 2020-09-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0009_maritalregime_maritalregimeinvestor'),
        ('clients', '0014_clients_marital_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.States'),
        ),
    ]
