# Generated by Django 3.0.4 on 2020-09-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0010_propertytype_propertytypeinvestor'),
        ('clients', '0015_auto_20200914_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsaddress',
            name='property_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='catalogues.PropertyType'),
            preserve_default=False,
        ),
    ]
