# Generated by Django 3.0.4 on 2020-09-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_clientsaddress_ubication_references1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsaddress',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', verbose_name='cliente'),
        ),
    ]
