# Generated by Django 3.0.4 on 2020-09-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20200922_0012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together={('RFC', 'CURP')},
        ),
    ]
