# Generated by Django 3.0.4 on 2020-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_auto_20200928_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='mother_lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='apellido materno'),
        ),
    ]
