# Generated by Django 3.0.4 on 2020-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20201111_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='CURP',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
    ]
