# Generated by Django 3.0.4 on 2020-08-27 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('key', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TCT001',
            },
        ),
        migrations.CreateModel(
            name='StatesInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalogues.States')),
            ],
            options={
                'db_table': 'TCP001',
            },
        ),
    ]
