# Generated by Django 3.0.4 on 2020-08-27 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statesinvestor',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='StatesInvestorCreatedBy', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statesinvestor',
            name='deactivated_by',
            field=models.ForeignKey(db_column='deactivated_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='StatesInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statesinvestor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='description',
            field=models.CharField(max_length=31),
        ),
    ]
