# Generated by Django 3.0.4 on 2020-08-27 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0002_auto_20200827_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='statesinvestor',
            name='deactivation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='statesinvestor',
            name='deactivated_by',
            field=models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='StatesInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
