# Generated by Django 3.0.4 on 2020-08-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_auto_20200827_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statesinvestor',
            name='deactivation_date',
        ),
        migrations.AddField(
            model_name='statesinvestor',
            name='deactivated_at',
            field=models.DateField(null=True),
        ),
    ]
