# Generated by Django 3.0.4 on 2020-08-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_auto_20200827_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('bank', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TCT002',
            },
        ),
    ]
