# Generated by Django 3.0.4 on 2020-11-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0013_identifications_identificationsinvestor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='identificationsinvestor',
            table='TCZ009',
        ),
    ]
