# Generated by Django 3.0.4 on 2020-11-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0014_auto_20201104_2204'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='identifications',
            table='TCT009',
        ),
    ]
