# Generated by Django 3.0.4 on 2020-11-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0015_auto_20201104_2204'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='identificationsinvestor',
            table='TCP009',
        ),
    ]
