# Generated by Django 3.0.4 on 2020-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0016_auto_20201104_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
