# Generated by Django 3.0.4 on 2020-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0017_states_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
