# Generated by Django 3.0.4 on 2020-11-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0018_banks_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='identifications',
            table='TCT_009',
        ),
        migrations.AlterModelTable(
            name='identificationsinvestor',
            table='TCP_009',
        ),
    ]
