# Generated by Django 3.0.4 on 2020-11-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0019_auto_20201123_1400'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='identifications',
            table='TCT009',
        ),
        migrations.AlterModelTable(
            name='identificationsinvestor',
            table='TCP009',
        ),
    ]
