# Generated by Django 3.0.4 on 2020-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0019_applicationstatus_comercialreferencetype_countrys_discountperiod_dispersiontype_educationallevel_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrys',
            name='country',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
