# Generated by Django 3.0.4 on 2020-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0020_auto_20201123_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifications',
            name='campox',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
