# Generated by Django 3.0.4 on 2020-11-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0021_identifications_campox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifications',
            name='campox',
        ),
    ]
