# Generated by Django 3.0.4 on 2020-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0021_auto_20201211_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsorigin',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
