# Generated by Django 3.0.4 on 2020-12-11 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investors', '0001_initial'),
        ('catalogues', '0022_auto_20201211_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='SectorInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SectorInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.Sector')),
            ],
            options={
                'db_table': 'TCP012',
            },
        ),
        migrations.CreateModel(
            name='SectorActivityInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='SectorActivityInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SectorActivityInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
                ('sector_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.SectorActivity')),
            ],
            options={
                'db_table': 'TCP013',
            },
        ),
        migrations.CreateModel(
            name='NationalityInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='NationalityInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NationalityInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.Nationality')),
            ],
            options={
                'db_table': 'TCP011',
            },
        ),
        migrations.CreateModel(
            name='JobTypeInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='JobTypeInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='JobTypeInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.JobType')),
            ],
            options={
                'db_table': 'TCP016',
            },
        ),
        migrations.CreateModel(
            name='FundsOriginInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='FundsOriginInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FundsOriginInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('funds_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.FundsOrigin')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP021',
            },
        ),
        migrations.CreateModel(
            name='FundsDestinationInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='FundsDestinationInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FundsDestinationInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('funds_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.FundsDestination')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP020',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTypeInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='EmployeeTypeInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EmployeeTypeInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.EmployeeType')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP014',
            },
        ),
        migrations.CreateModel(
            name='EducationalLevelInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='EducationalLevelInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EducationalLevelInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.EducationalLevel')),
            ],
            options={
                'db_table': 'TCP010',
            },
        ),
        migrations.CreateModel(
            name='DispersionTypeInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='DispersionTypeInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DispersionTypeInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('dispersion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.DispersionType')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP017',
            },
        ),
        migrations.CreateModel(
            name='DiscountPeriodInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='DiscountPeriodInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DiscountPeriodInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('discount_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.DiscountPeriod')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP019',
            },
        ),
        migrations.CreateModel(
            name='CountrysInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('Countrys', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.Countrys')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='CountrysInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CountrysInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP018',
            },
        ),
        migrations.CreateModel(
            name='ComercialReferenceInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('comercial_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.ComercialReferenceType')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='ComercialReferenceInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComercialReferenceInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP015',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('investor_key', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateField(null=True)),
                ('application_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.ApplicationStatus')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='ApplicationStatusInvestorCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ApplicationStatusInvestorDeactivateddBy', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.Investors')),
            ],
            options={
                'db_table': 'TCP022',
            },
        ),
    ]
