# Generated by Django 3.0.4 on 2020-06-04 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=25, verbose_name='nombre del fondeador')),
                ('account_number', models.CharField(max_length=20, verbose_name='número de cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'db_table': 'TI015',
            },
        ),
        migrations.CreateModel(
            name='InvestorsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('address_name', models.CharField(max_length=30, verbose_name='identificador')),
                ('street', models.CharField(max_length=50, verbose_name='calle')),
                ('ext_number', models.CharField(max_length=15, verbose_name='numero exterior')),
                ('int_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='numero interior')),
                ('suburb', models.CharField(max_length=50, verbose_name='colonia')),
                ('zip_code', models.CharField(max_length=5, verbose_name='codigo Postal')),
                ('city', models.CharField(max_length=25, verbose_name='ciudad')),
                ('state', models.CharField(max_length=25, verbose_name='estado')),
                ('phone_contact', models.CharField(max_length=13, verbose_name='telefono de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de desactivación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_address_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deactivated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_address_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='desactivado por')),
                ('investor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investors.Investors', verbose_name='fondeador')),
            ],
            options={
                'db_table': 'TIA016',
            },
        ),
    ]
