# Generated by Django 3.0.4 on 2020-06-02 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreements',
            name='signature_date',
        ),
        migrations.AddField(
            model_name='agreements',
            name='apply_retribution',
            field=models.BooleanField(default=False, verbose_name='aplica reciprocidad'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='costo del convenio'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha de fin del convenio'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='retribution_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='cantidad de la reciprocidad'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='retribution_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='reciprocidad por dentro/fuera'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de inicio del convenio'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='discount_key',
            field=models.CharField(max_length=50, verbose_name='clave de descuento'),
        ),
    ]
