# Generated by Django 3.0.4 on 2020-09-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffices',
            name='external_id',
            field=models.CharField(default='X', max_length=6, verbose_name='Clave externa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchoffices',
            name='municipality',
            field=models.CharField(default='X', max_length=50, verbose_name='municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchoffices',
            name='city',
            field=models.CharField(max_length=50, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='branchoffices',
            name='ext_number',
            field=models.CharField(max_length=50, verbose_name='numero exterior'),
        ),
        migrations.AlterField(
            model_name='branchoffices',
            name='int_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numero interior'),
        ),
        migrations.AlterField(
            model_name='branchoffices',
            name='state',
            field=models.CharField(max_length=35, verbose_name='estado'),
        ),
    ]
