# Generated by Django 3.0.4 on 2020-09-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20200919_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffices',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre de la sucursal'),
        ),
        migrations.AlterField(
            model_name='branchoffices',
            name='phone_contact',
            field=models.CharField(max_length=10, verbose_name='telefono de contacto'),
        ),
    ]
