# Generated by Django 3.0.4 on 2020-09-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0011_relationships_relationshipsinvestor'),
        ('offices', '0003_auto_20200919_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchoffices',
            options={},
        ),
        migrations.AlterField(
            model_name='branchoffices',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.States'),
        ),
        migrations.AlterModelTable(
            name='branchoffices',
            table='TBO001',
        ),
    ]
