# Generated by Django 3.0.4 on 2020-06-10 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=80, verbose_name='nombre del asesor')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone_contact', models.CharField(max_length=13, verbose_name='teléfono de contacto')),
                ('status', models.CharField(max_length=20, verbose_name='estatus')),
                ('bank', models.CharField(max_length=30, verbose_name='banco')),
                ('account_number', models.CharField(max_length=30, verbose_name='número de cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_user_id', to=settings.AUTH_USER_MODEL, verbose_name='clave de usuario')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvisersPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('state', models.CharField(max_length=30, verbose_name='plaza')),
                ('city', models.CharField(max_length=50, verbose_name='localidad')),
                ('adviser_id', models.ManyToManyField(related_name='adviser_id', to='advisers.Advisers', verbose_name='clave del asesor')),
                ('supervisor_user_id', models.ManyToManyField(related_name='supervisor_user_id', to=settings.AUTH_USER_MODEL, verbose_name='clave del supervisor')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
