# Generated by Django 3.0.4 on 2020-09-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0011_relationships_relationshipsinvestor'),
        ('advisers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisers',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.Banks'),
        ),
        migrations.AlterField(
            model_name='advisersplaces',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.States'),
        ),
    ]
