# Generated by Django 3.0.4 on 2020-09-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisers', '0002_auto_20200923_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='advisersplaces',
            options={},
        ),
        migrations.AlterModelTable(
            name='advisers',
            table='TAD001',
        ),
        migrations.AlterModelTable(
            name='advisersplaces',
            table='TAD002',
        ),
    ]
