# Generated by Django 3.0.4 on 2020-08-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200528_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='min_term',
        ),
        migrations.AlterField(
            model_name='products',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='monto mínimo'),
        ),
    ]
