# Generated by Django 3.0.4 on 2020-08-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200814_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='max_term',
        ),
        migrations.AddField(
            model_name='products',
            name='term',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='plazo'),
        ),
    ]
