# Generated by Django 3.0.4 on 2020-08-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200814_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='external_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
