# Generated by Django 3.0.4 on 2020-08-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_agreementinvestors'),
        ('products', '0007_products_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.Agreements', verbose_name='convenio'),
        ),
    ]
