# Generated by Django 3.0.4 on 2020-09-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200817_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='agreement',
        ),
    ]
