# Generated by Django 3.0.4 on 2020-09-12 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_auto_20200824_1703'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_remove_products_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de desactivación')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.Agreements')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agree_prod_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deactivated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agree_prod_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='desactivada por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
            options={
                'db_table': 'TRAP008',
            },
        ),
    ]
