# Generated by Django 3.0.4 on 2020-09-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productsinvestor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agreement_product',
            table='TPR008',
        ),
        migrations.AlterModelTable(
            name='products',
            table='TPR006',
        ),
    ]
