# Generated by Django 3.0.4 on 2020-09-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200923_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='productsinvestor',
            name='investor_key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
